version: "3.8"
services:
  db:
    image: mysql:8.0
    container_name: trp_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword123
      MYSQL_DATABASE: tea_round_picker
      MYSQL_USER: trp_user
      MYSQL_PASSWORD: trp_pass_123
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d:ro

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8081:8080"

volumes:
  db_data:
